apiVersion: apps/v1
kind: Deployment
metadata:
  name: alerts-consumer
  namespace: team-operations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alerts-consumer
  template:
    metadata:
      labels:
        app: alerts-consumer
    spec:
      containers:
        - name: consumer
          image: kafka-alerts-consumer:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: kafka-connection
          env:
            - name: CONSUMER_GROUP
              value: "alerts-consumer"
            - name: TOPIC
              value: "delivery.alerts"
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: alerts-consumer-kafka-creds
                  key: api_key_id
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: alerts-consumer-kafka-creds
                  key: api_key_secret
