apiVersion: platform.girishn.cloud/v1alpha1
kind: KafkaTopicClaim
metadata:
  name: delivery-alerts
  namespace: team-operations
spec:
  topicName: delivery.alerts
  partitions: 3
  consumerName: alerts-consumer
  valueSchema: delivery.alerts-value
  schemaBody: >-
    {"type":"record","name":"DeliveryAlert","namespace":"com.logistics.alerts","fields":[{"name":"shipment_id","type":"string"},{"name":"alert_type","type":"string"},{"name":"severity","type":"string"},{"name":"message","type":"string"},{"name":"timestamp","type":"long"}]}
