apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipments-producer
  namespace: team-logistics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipments-producer
  template:
    metadata:
      labels:
        app: shipments-producer
    spec:
      containers:
        - name: producer
          image: kafka-producer:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: kafka-connection
          env:
            - name: SHIPMENTS_TOPIC
              value: "shipments.events"
            - name: ALERTS_TOPIC
              value: "delivery.alerts"
            - name: RATE_PER_SEC
              value: "10"
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: producer-kafka-creds
                  key: api_key_id
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: producer-kafka-creds
                  key: api_key_secret
