apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracking-consumer
  namespace: team-logistics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracking-consumer
  template:
    metadata:
      labels:
        app: tracking-consumer
    spec:
      containers:
        - name: consumer
          image: kafka-tracking-consumer:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: kafka-connection
          env:
            - name: CONSUMER_GROUP
              value: "tracking-consumer"
            - name: TOPIC
              value: "shipments.events"
            - name: PROCESS_DELAY_SEC
              value: "1.0"
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: tracking-consumer-kafka-creds
                  key: api_key_id
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: tracking-consumer-kafka-creds
                  key: api_key_secret
